### ISSUE TITLE
Updating ArchLinux

### ISSUE THREAD

**Issue by bebehei** [tmc/dockerfiles#11]
Hi @tmc,

would you mind updating the ArchLinux system? ArchLinux got major changes during the past year, which often required manual changes. So the current docker image is unusable in terms of compatibility.

Although you're not in debt to do this, it would help the docker infrastructure. The problem is, that this image is available on docker hub via `base/archlinux`. Albeit `base` is not an official name on docker hub, most people get tricked into thinking, cause no real official image is available.

Although you're not liable, I'd request to update the docker images.

If any PRs would help, I'd be glad helping you with this.

## Some stats worth to consider

All packages:
```
[root@arch /]# pacman -Q | wc -l
96
```

Upgrade process: Look at

- the 108 packages to install
- the requested download size
- ...

```
[root@dcbde0a4afbf /]# pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
:: Replace dirmngr with core/gnupg? [Y/n]
:: Replace libdbus with core/dbus? [Y/n]
:: Replace lzo2 with core/lzo? [Y/n]
resolving dependencies...
looking for inter-conflicts...

Packages (108): acl-2.2.52-3  archlinux-keyring-20161201-1  attr-2.4.47-2  bash-4.4.005-1  ca-certificates-20160507-1  ca-certificates-cacert-20140824-4  ca-certificates-mozilla-3.27.2-1
                ca-certificates-utils-20160507-1  coreutils-8.26-1  cracklib-2.9.6-1  curl-7.51.0-2  db-5.3.28-3  dbus-1.10.14-1  device-mapper-2.02.168-1  dhcpcd-6.11.3-1  diffutils-3.5-1
                dirmngr-1.1.1-2 [removal]  e2fsprogs-1.43.3-1  expat-2.2.0-2  file-5.29-1  filesystem-2016.12-2  findutils-4.6.0-2  gawk-4.1.4-2  gcc-libs-6.2.1-1  gdbm-1.12-2  gettext-0.19.8.1-2
                glib2-2.50.2-1  glibc-2.24-2  gmp-6.1.1-1  gnupg-2.1.16-1  gnutls-3.4.17-1  gpgme-1.7.1-2  grep-2.26-1  gzip-1.8-2  hwids-20161103-1  iana-etc-20161101-1  icu-58.2-1  inetutils-1.9.4-5
                iproute2-4.8.0-1  iptables-1.6.0-1  iputils-20161105.1f2bb12-1  kbd-2.0.3-1  kmod-23-1  krb5-1.13.7-1  less-487-1  libarchive-3.2.1-2  libassuan-2.4.3-1  libcap-2.25-1  libdbus-1.8.6-1 [removal]
                libelf-0.167-1  libffi-3.2.1-2  libgcrypt-1.7.3-1  libgpg-error-1.25-1  libidn-1.33-1  libksba-1.3.4-2  libldap-2.4.44-2  libmnl-1.0.4-1  libnftnl-1.0.6-1  libpsl-0.15.0-6  libsasl-2.1.26-8
                libseccomp-2.3.1-1  libsecret-0.18.5-1  libssh2-1.8.0-1  libsystemd-232-6  libtasn1-4.9-2  libtirpc-1.0.1-2  libunistring-0.9.6-2  libusb-1.0.21-1  libutil-linux-2.28.2-2
                linux-api-headers-4.7-1  logrotate-3.10.0-1  lz4-1:1.7.4.2-1  lzo-2.09-1  lzo2-2.08-1 [removal]  mpfr-3.1.5-1  nano-2.7.1-1  ncurses-6.0+20161203-1  netctl-1.12-2  nettle-3.3-1  npth-1.3-1
                openresolv-3.8.1-1  openssl-1.0.2.j-1  p11-kit-0.23.2-1  pacman-5.0.1-4  pacman-mirrorlist-20161211-1  pam-1.3.0-1  pcre-8.39-2  perl-5.24.0-2  pinentry-1.0.0-1  popt-1.16-8  procps-ng-3.3.12-1
                psmisc-22.21-3  readline-7.0.001-1  run-parts-4.8.1-1  sed-4.2.2-4  shadow-4.4-3  sqlite-3.15.2-1  systemd-232-6  systemd-sysvcompat-232-6  tar-1.29-2  texinfo-6.3-1  tzdata-2016j-1
                usbutils-008-1  util-linux-2.28.2-2  vi-1:070224-2  which-2.21-2  xz-5.2.2-2  zlib-1:1.2.8-7

Total Download Size:    40.92 MiB
Total Installed Size:   406.42 MiB
Net Upgrade Size:       148.92 MiB

:: Proceed with installation? [Y/n] ^C
```

**Comment by dumblob** [comment]
There is another repo with an up to date dockerfile: https://github.com/bebehei/archlinux-docker .

**Comment by bebehei** [comment]
@tmc Could you please just give a small message expressing your (dis)interest. This would be great.

I don't know how to reach out to you [else](https://twitter.com/bebehei/status/830911984447127554).

Just a small sentence like
- I'm not interested.
- Create a proper PR and I'll click on merge.
- I can add you on dockerhub to the repo as collaborator.

would suffice. At least it would clarify basic questions.

**Comment by bebehei** [comment]
@dumblob That's my own repo. And actually I have founded an organisation on [GitHub](https://github.com/archimg) and on [Docker Hub](https://hub.docker.com/u/archimg/), which images get built by [TravisCI](https://travis-ci.org/archimg/) with a daily cronjob.

**Comment by tmc** [comment]
@bebehei contacting you to help get this better supported.

**Comment by bebehei** [comment]
From now on, images are updated on a daily basis. Thank you @tmc

**Comment by dumblob** [comment]
@bebehei @tmc which of the following images are updated on a daily basis and which will be maintained in the future? I'm confused :cry:.

As of 2017-02-27 13:24:58 UTC+1:

docker image | updated | maintained in the near future
--- | :---: | :---:
archimg/base | daily (Travis CI) | yes (@archimg)
archimg/base-devel | daily (Travis CI) | yes (@archimg)
archimg/archlinux-pkgbuilder | on push | yes (dockerhub)
base/archlinux | daily (Travis CI) | yes (@archimg)
base/arch | ? | ?
base/devel | daily (Travis CI) | yes (@archimg)

**Comment by bebehei** [comment]
All images from @archimg will be maintained.

mirrors: `archimg/base`, `base/archlinux`, built by travis-CI ➡️ updated daily, maintained

mirrors: `archimg/base-devel`, `base/devel`, built by travis-CI ➡️ updated daily, maintained

`archimg/archlinux-pkgbuilder` is not a basic ArchLinux image. It's a docker image to build packages from PKGBUILDs. This one is built by dockerhub ➡️ updated on push, maintained

I have not been aware of `base/arch`. I may ask @tmc to get access to this repo, too. So then at the end, this should also be a mirror of `base/archlinux` and `archimg/base`.

Sry, I can't edit your table.

**Comment by dumblob** [comment]
I've updated the [table](https://github.com/tmc/dockerfiles/issues/11#issuecomment-282690874 ). In case anything should change, please comment in this thread.

**Comment by bebehei** [comment]
Although they've got both the same name, @tmc != Travis CI. All images will get maintained by @archimg. Please comment on those git-repos in future. This repo here has nothing to do anymore with `base/archlinux` and `base/devel`.

**Comment by dumblob** [comment]
I've updated the [table](https://github.com/tmc/dockerfiles/issues/11#issuecomment-282690874 ). Should it not match the current state, please comment further.
