### ISSUE TITLE
Cannot build chefserver container

### ISSUE THREAD

**Issue by jcortejoso** [tmc/dockerfiles#3]
Hi! I am having some problems trying to generate a docker container with chefserver using the dockerfile provided. I have clone the repo and when I try to generate the container (command `'docker build -t chefserver chef-server/'`) it sticks in STEP 9 doing the chef-server-ctl reconfigure. The last line it shows is `'[2014-08-04T11:17:00+00:00] INFO: link[/opt/chef-server/service/rabbitmq] created'`.

I had tried to install chef-server manually in some containers and it got stuck also doing the chef-server-ctl in `'ruby_block[supervise_rabbitmq_sleep]'`. It's two actions later in chef execution but I think both tries stop in that point but I see two lines before when building the container.

Any help with the issue? I have been able to run chef-server pulling the image from docker hub but I was wondering to install it and build manually the container.

Thanks!

**Comment by xmik** [comment]
It worked for me, when I ran: `docker run -dti --privileged ubuntu:14.04` and then inside the container:
```
root@container_id:/# apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y wget 
root@container_id:/# cd /tmp && wget --content-disposition "http://www.opscode.com/chef/download-server?p=ubuntu&pv=12.04&m=x86_64&v=latest&prerelease=false&nightlies=false"
root@container_id:/# dpkg -i /tmp/chef-server*.deb
root@container_id:/# /opt/chef-server/embedded/bin/runsvdir-start &
root@1b78eaf2bbf9:/# chef-server-ctl reconfigure
```

`--privileged` seems to solve this problem. However, currently `docker build` does not support this option [#1916](https://github.com/docker/docker/issues/1916).
