### ISSUE TITLE
mkimage-arch.sh gives "failed to setup API filesystems in chroot..." error

### ISSUE THREAD

**Issue by Nasicus** [tmc/dockerfiles#6]
Hi

I'm trying to build my own docker base image from an ArchLinux (64bit, latest release (2014.11.01), all updates done via `pacman -Syu`). 
I'm using is the official script which I found here: https://registry.hub.docker.com/u/base/archlinux/ --> https://github.com/docker/docker/blob/master/contrib/mkimage-arch.sh .

I'm executing this script (together with the `mkimage-arch-pacman.conf`) from a "real" ArchLinux (VirtualBox) as root.

I always get the error:
    
    .....
    ==> Updating trust database...
    gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
    gpg: depth: 0 valid: 1 signed: 5 trust: 0-, 0q, 0n, 0m, 0f, 1u
    gpg: depth: 1 valid: 5 signed: 61 trust: 0-, 0q, 0n, 5m, 0f, 0u
    gpg: depth: 2 valid: 60 signed: 4 trust: 60-, 0q, 0n, 0m, 0f, 0u
    gpg: next trustdb check due at 2015-03-31
    umount: /var/tmp/rootfs-archlinux-fORD04yCL0/dev: target is busy
    (In some cases useful info about processes that
    use the device is found by lsof(8) or fuser(1).)
    umount: /var/tmp/rootfs-archlinux-fORD04yCL0: target is busy
    (In some cases useful info about processes that
    use the device is found by lsof(8) or fuser(1).)
    mount: udev is already mounted or /var/tmp/rootfs-archlinux-fORD04yCL0/dev busy
    udev is already mounted on /var/tmp/rootfs-archlinux-fORD04yCL0/dev
    udev is already mounted on /var/tmp/rootfs-archlinux-fORD04yCL0/dev
    ==> ERROR: failed to setup API filesystems in chroot /var/tmp/rootfs-archlinux-fORD04yCL0 

It looks like the error happens in line `39` in the `mkimage-arch.sh` script:

    arch-chroot $ROOTFS /bin/sh -c "haveged -w 1024; pacman-key --init; pkill haveged; pacman -Rs --noconfirm haveged; pacman-key --populate archlinux"

I really have no idea what I should/could do about this. I tried googling it, I tried asking in archlinux and docker IRC but nobody could help me.
I'm not a linux guru so I have no idea what could be wrong in this script, as far as I can see it looks fine to me.
Also I almost can't believe, that the official script contains an error.

Maybe my ArchLinux needs to be set up in a special way or something like that?

Thanks in advance for any help!

Reference post:
https://forums.docker.com/t/creating-base-image-from-archlinux-script-not-working/

**Comment by shingonoide** [comment]
@Nasicus @ztombol I guess this issue happens because of expect timeout option.
Archlinux wiki article (https://wiki.archlinux.org/index.php/Docker) suggests to run `sed -i 's/timeout 60/timeout 120/' mkimage-arch.sh` to change that value for slow network or cpu.

Is my case I changed to `timeout 200` and works pretty well, but I think this value could be even more.

**Comment by tmc** [comment]
I'm closing this as that upstream fix has landed.
