### ISSUE TITLE
Any chance to update base/archlinux?

### ISSUE THREAD

**Issue by cronopio** [tmc/dockerfiles#7]
Hi

Some many people including me been waiting for a new release of the docker image of `base/archlinux`
Is there any chance to know if you will update the image at sometime?

Thanks!

PS: Comments about it on https://registry.hub.docker.com/u/base/archlinux/

**Comment by cboettig** [comment]
+1

**Comment by tmc** [comment]
Updated.

**Comment by cronopio** [comment]
Awesome! thanks!

**Comment by simonsmiley** [comment]
the update isn't reflected on docker hub. there it's still 2014.07.03
